spring:
  datasource:
    url: jdbc:mysql://localhost:16033/talentSix?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用hikariCP作为连接池
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 连接池中维护的最小空闲连接数
      minimum-idle: 10
      # 最大连接池大小
      maximum-pool-size: 25
      # 从连接池返回的连接的默认自动提交行为
      auto-commit: true
      # 允许连接在连接池中空闲的最长时间（以毫秒为单位）
      idle-timeout: 30000
      # 连接池中连接关闭后的最长生命周期（以毫秒为单位）
      max-lifetime: 1800000
      # 客户端等待连接池连接的最大毫秒数
      connection-timeout: 30000
      # 心跳检测
      connection-test-query: SELECT 1
      # 连接池名称
      pool-name: TalentSixHikariCP

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#允许跨域的网址
cors-config:
  allowedOrigins:
  - http://localhost:8888
  - http://127.0.0.1:8888